### ISSUE TITLE
Getting issue while running with tls_disble =1 

### ISSUE THREAD

**Issue by shaundevops** [Sakib37/DevOps#4]
Getting issue while running on EKS

```
Events:
  Type     Reason               Age                    From                                              Message
  ----     ------               ----                   ----                                              -------
  Warning  Failed               49m                    kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Failed to pull image "accso/docker-awscli": rpc error: code = Unknown desc = context canceled
  Warning  Failed               49m                    kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Error: ErrImagePull
  Normal   Pulling              49m                    kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Pulling image "vault:1.0.3"
  Normal   Pulled               41m                    kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Successfully pulled image "vault:1.0.3"
  Normal   Pulling              40m (x2 over 93m)      kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Pulling image "accso/docker-awscli"
  Normal   Pulled               3m54s                  kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Successfully pulled image "accso/docker-awscli"
  Normal   Started              3m49s                  kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Started container token-manager
  Normal   Created              3m49s                  kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Created container token-manager
  Normal   Created              3m3s (x4 over 41m)     kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Created container vault
  Normal   Started              3m3s (x4 over 41m)     kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Started container vault
  Normal   Pulled               3m3s (x3 over 3m49s)   kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Container image "vault:1.0.3" already present on machine
  Warning  FailedPostStartHook  3m2s (x4 over 41m)     kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Exec lifecycle hook ([/bin/sh -c sleep 5  &&  vault operator init | grep ": [A-Za-z0-9+(?<=).+\/]*$" > /vault-token/vault-token-key || true]) for Container "vault" in Pod "vault-0_vault(8faa6a67-8468-11ea-a018-06e296d3c412)" failed - error: command '/bin/sh -c sleep 5  &&  vault operator init | grep ": [A-Za-z0-9+(?<=).+\/]*$" > /vault-token/vault-token-key || true' exited with 137: , message: ""
  Normal   Killing              3m2s (x4 over 41m)     kubelet, ip-10-0-1-9.cn-north-1.compute.internal  FailedPostStartHook
  Warning  BackOff              2m50s (x7 over 3m47s)  kubelet, ip-10-0-1-9.cn-north-1.compute.internal  Back-off restarting failed container
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  serviceName: "vault"
  selector:
    matchLabels:
      app: vault
  replicas: 3
  template:
    metadata:
      labels:
        app: vault
      #annotations:
      #  iam.amazonaws.com/role: ${VAULT_IAM_ROLE_ARN}
    spec:
      serviceAccountName: vault
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vault
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                 matchExpressions:
                   - key: app
                     operator: In
                     values:
                       - vault
              topologyKey: failure-domain.beta.kubernetes.io/zone
      initContainers:
        - name: config
          image: busybox
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_AWS_REGION
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_DYNAMODB_TABLE_NAME
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_CLUSTER_NAME
          command: ["/bin/sh", "-c"]
          args:
            - |
              cat > /etc/vault/config/vault.hcl <<EOF
              cluster_name= "${CLUSTER_NAME}"
              max_lease_ttl = "768h"
              default_lease_ttl = "768h"

              disable_clustering = "False"

              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_disable = "1"
                #tls_cert_file = "/etc/vault/tls/tls.crt"
                #tls_key_file = "/etc/vault/tls/tls.key"
                #tls_min_version = "tls12"
              }

              storage "dynamodb" {
                ha_enabled = "True"
                region = "${AWS_REGION}"
                table = "${DYNAMODB_TABLE_NAME}"
                read_capacity = "10"
                write_capacity = "5"
              }

              seal "awskms" {
              }

              ui = true
              EOF
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
      containers:
        - name: token-manager
          image: accso/docker-awscli
          env:
            - name: VAULT_KMS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_KMS_KEY_ID
            - name: VAULT_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_S3_BUCKET_NAME
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_AWS_REGION
          volumeMounts:
            - name: vault-token
              mountPath: /vault-token
            - name: vault-token-manager
              mountPath: /vault-token-manager
          command:
            - "/bin/bash"
            - "/vault-token-manager/token-manager.sh"
        - name: vault
          image: "vault:1.0.3"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: VAULT_API_ADDR
              value: "https://${VAULT_ENDPOINT}"
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(POD_IP):8201"
            - name: VAULT_ADDR
              value: "https://$(POD_IP):8200"
            - name:  VAULT_SKIP_VERIFY
              value: "1"
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_AWS_REGION
            - name: VAULT_AWSKMS_SEAL_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_KMS_KEY_ID
            - name: AWS_KMS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: VAULT_KMS_VPC_ENDPOINT
          args:
            - "server"
            - "-config=/etc/vault/config/vault.hcl"
            - "-log-level=debug"
          ports:
            - name: http
              containerPort: 8200
              protocol: "TCP"
            - name: server
              containerPort: 8201
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/v1/sys/health?standbyok=true"
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sleep 5  &&  \
                         vault operator init"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault/config
            #- name: vault-tls
            #  mountPath: /etc/vault/tls
            - name: vault-token
              mountPath: /vault-token
      volumes:
        - name: vault-config
          emptyDir: {}
        - name: vault-token
          emptyDir: {}
        #- name: vault-tls
        #  secret:
        #    secretName: vault-tls
        - name: vault-token-manager
          configMap:
            name: vault-token-manager
```
